name: ACA - Update Container Image
on: 
  workflow_dispatch:
    inputs:
      imagetag:
        type: string
        required: false
        default: "latest"

permissions:
      id-token: write
      contents: read

jobs: 
  deploy:

    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Update Running Image
        uses: azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: ghcr.io/andrejvysny/example:${{ github.event.inputs.imagetag }}
          containerAppName: <APP_NAME>
          resourceGroup: <RG_NAME>
