name: ACA - Update Container Image
on: 
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Update Running Image
        uses: azure/container-apps-deploy-action@v2
        with:
        # TODO: option 1: deploy always latest image.

        # TODO: option 2: choose which image to deploy - when not selected -> deploy latest 
        # neets to find out how to choose images from github registry

          imageToDeploy: ghcr.io/andrejvysny/complex-fe
          containerAppName: aca-dev-frontend
          resourceGroup: rg-myapp-dev-swedencentral
