name: Build image and push to GitHub Container Registry

on:
  workflow_call:
    inputs:
      dockerfile:
        required: false
        default: Dockerfile
        type: string
      context:
        required: false
        type: string
        default: .
      target:
        required: false
        type: string
        default: null
      tags:
        required: true
        type: string
    secrets:
      access_token:
        required: true


jobs:
  build_and_push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ inputs.access_token }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          tags: ${{ inputs.tags }}
          push: true
          target: ${{ inputs.target }}
          file: ${{ inputs.dockerfile }}

      - name: Image data
        run: |
          echo "Image Id: ${{ steps.docker_build.outputs.imageid }}" 
          echo "Image Digest: ${{ steps.docker_build.outputs.digest }}" 
          echo "Image Metadata: ${{ steps.docker_build.outputs.metadata }}"